import Head from "next/head";
import { useMoralis } from "react-moralis";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { isAuthenticated } = useMoralis();

  return (
    <div className={styles.container}>
      <Head>
        <title>Chat With Metaverse</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div></div>
    </div>
  );
}
